### ISSUE TITLE
로그인요청 에러처리

### ISSUE THREAD

**Issue by 0hhanum** [CSID-DGU/2022-1-CSC4031-Kloud#36]
FE 측 로그인 실패시 계속 서버 다운됨

**Comment by kshshkim** [comment]
이리저리 테스트를 해보았으나, 서버가 다운되는 상황을 찾지 못했습니다. 혹시 어떤 데이터를 넣었을 때 다운되는지 알 수 있을까요?

**Comment by 0hhanum** [comment]
해결완료
